### ISSUE TITLE
'Graph' object has no attribute 'nodes_iter' Error

### ISSUE THREAD

**Issue by ay27** [priba/nmp_qc#4]
When I followed the installation that installed rdkit and all other requirements, and downloaded the data, run the "python main.py", I got the error below. Does there something error in the code?

```
Prepare files
Define model
Traceback (most recent call last):
  File "/home/ay27/repo/nmp_qc/main.py", line 320, in <module>
    main()
  File "/home/ay27/repo/nmp_qc/main.py", line 103, in main
    g_tuple, l = data_train[0]
  File "/home/ay27/repo/nmp_qc/datasets/qm9.py", line 47, in __getitem__
    h = self.vertex_transform(g)
  File "/home/ay27/repo/nmp_qc/datasets/utils.py", line 28, in qm9_nodes
    for n, d in g.nodes_iter(data=True):
AttributeError: 'Graph' object has no attribute 'nodes_iter'
```

**Comment by MehmetTopsakal** [comment]
I think some stuff has changed with networkx 2.0.
Maybe you should try " conda install networkx=1.11 "

**Comment by ay27** [comment]
Wow, problem solved! Thank you very much!

**Comment by adamxyang** [comment]
Or could also change `nodes_iter()` and `edges_iter()` to `nodes()` and `edges()`.
